/** Writes CREDITS.md from the photo slots in site.ts plus the fonts, icons and logo sources. */
import { writeFile } from "node:fs/promises";
import { images } from "../src/content/site";
import type { ImageSlot } from "../src/shared/types";

const slots: ImageSlot[] = Object.values(images);
const photos = slots
  .filter(
    (slot): slot is ImageSlot & { credit: NonNullable<ImageSlot["credit"]> } =>
      slot.credit !== undefined,
  )
  .map(
    (slot) =>
      `| \`${slot.id}\` | ${slot.alt} | ${slot.credit.photographer} | ${slot.credit.license} | ${slot.credit.source} |`,
  );

const doc = `# Credits

Generated by \`npm run credits\` from \`src/content/site.ts\`.

## Photos

Both Roberts International Airport photos really are Liberia. The two CC0 photos are generic travel images and are never captioned or described as Liberia. CC BY-SA photos must keep this attribution wherever they are used.

| Slot | What it shows | Photographer | License | Source |
| --- | --- | --- | --- | --- |
${photos.join("\n")}

## Fonts (self-hosted, subset)

| Font | Used in | License |
| --- | --- | --- |
| Playfair Display | Design A headings | SIL Open Font License 1.1 |
| Poppins | Design A body | SIL Open Font License 1.1 |
| Cinzel (digits only) | Design A step numbers | SIL Open Font License 1.1 |
| Big Shoulders Display | Design B headings and board | SIL Open Font License 1.1 |
| Atkinson Hyperlegible | Design B body | SIL Open Font License 1.1 |

Font files come from the Fontsource packages on npm.

## Icons

- WhatsApp, Facebook and Instagram glyphs: Simple Icons, CC0 1.0.
- All other icons were drawn for this site.

## Logo

Tarley Travel LLC's own logo (\`reference/logo-a.jpg\`), cropped and resized but never redrawn or recolored.
`;

await writeFile("CREDITS.md", doc);
console.log(`CREDITS.md: ${photos.length} photos`);
