/**
 * Generates PLACEHOLDERS.md from the built site, so the page list is always exact:
 * every [BRACKETED] placeholder and every empty photo slot, where it appears and
 * what Tarley needs to supply. Run after `npm run build`.
 */
import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { factsToConfirm, images, placeholders } from "../src/content/site";

const DIST = "dist";

async function htmlFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map((entry) => {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) return htmlFiles(full);
      return Promise.resolve(entry.name.endsWith(".html") ? [full] : []);
    }),
  );
  return nested.flat();
}

const toRoute = (file: string) =>
  `/${path.relative(DIST, file)}`.replace(/\.html$/, "").replace(/\/index$/, "") || "/";

const decode = (s: string) =>
  s
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");

const tokenPages = new Map<string, Set<string>>();
const slotPages = new Map<string, Set<string>>();

for (const file of (await htmlFiles(DIST)).sort()) {
  const html = await readFile(file, "utf8");
  const route = toRoute(file);
  for (const match of html.matchAll(/data-placeholder[^>]*>([^<]+)</g)) {
    const token = decode(match[1] ?? "").trim();
    if (!tokenPages.has(token)) tokenPages.set(token, new Set());
    tokenPages.get(token)?.add(route);
  }
  for (const match of html.matchAll(/data-photo-slot="([^"]+)"/g)) {
    const id = match[1] ?? "";
    if (!slotPages.has(id)) slotPages.set(id, new Set());
    slotPages.get(id)?.add(route);
  }
}

const list = (pages: Set<string> | undefined) =>
  pages && pages.size > 0 ? [...pages].map((p) => `\`${p}\``).join(", ") : "not shown yet";

const textRows = Object.values(placeholders).map(
  (p) => `| ${p.token} | ${list(tokenPages.get(p.token))} | ${p.needs} |`,
);
const unknownTokens = [...tokenPages.keys()].filter(
  (t) => !Object.values(placeholders).some((p) => p.token === t),
);

const photoRows = Object.values(images)
  .filter((slot) => slotPages.has(slot.id))
  .map((slot) => `| \`${slot.id}\` | ${slot.caption} | ${list(slotPages.get(slot.id))} |`);

const doc = `# Placeholders Tarley needs to fill

Generated by \`npm run placeholders\` from the built site. Do not edit by hand; change \`src/content/site.ts\` and rebuild.

Every item below shows on the live pages as a visible, shaded placeholder, so nothing is guessed.

## Text

| Placeholder | Pages | What Tarley supplies |
| --- | --- | --- |
${textRows.join("\n")}
${unknownTokens.length > 0 ? `\n**Unregistered placeholders found:** ${unknownTokens.join(", ")}\n` : ""}
## Photos

Each slot shows its caption until a photo is added to \`assets/photos/{slot}.jpg\` and \`file\` is set on the slot in \`site.ts\`. Real Tarley photos replace any stock photo. Stock photos in use are listed in \`CREDITS.md\`.

| Slot | Shot needed | Pages |
| --- | --- | --- |
${photoRows.length > 0 ? photoRows.join("\n") : "| none | All slots have photos | |"}

## Facts to confirm

| Item | Current value | Why it needs a check |
| --- | --- | --- |
${factsToConfirm.map((f) => `| ${f.item} | ${f.value} | ${f.why} |`).join("\n")}
`;

await writeFile("PLACEHOLDERS.md", doc);
console.log(
  `PLACEHOLDERS.md: ${textRows.length} text placeholders, ${photoRows.length} photo slots`,
);
