/**
 * Generates PLACEHOLDERS.md: the interim copy and stock photos standing in for
 * Tarley's own content, any [BRACKETED] placeholder or empty photo slot still in
 * the built site, and the facts to confirm. Run after `npm run build`.
 */
import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { factsToConfirm, images, placeholders } from "../src/content/site";

const DIST = "dist";

async function htmlFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map((entry) => {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) return htmlFiles(full);
      return Promise.resolve(entry.name.endsWith(".html") ? [full] : []);
    }),
  );
  return nested.flat();
}

const toRoute = (file: string) =>
  `/${path.relative(DIST, file)}`.replace(/\.html$/, "").replace(/\/index$/, "") || "/";

const decode = (s: string) =>
  s
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");

const tokenPages = new Map<string, Set<string>>();
const slotPages = new Map<string, Set<string>>();

for (const file of (await htmlFiles(DIST)).sort()) {
  const html = await readFile(file, "utf8");
  const route = toRoute(file);
  for (const match of html.matchAll(/data-placeholder[^>]*>([^<]+)</g)) {
    const token = decode(match[1] ?? "").trim();
    if (!tokenPages.has(token)) tokenPages.set(token, new Set());
    tokenPages.get(token)?.add(route);
  }
  for (const match of html.matchAll(/data-photo-slot="([^"]+)"/g)) {
    const id = match[1] ?? "";
    if (!slotPages.has(id)) slotPages.set(id, new Set());
    slotPages.get(id)?.add(route);
  }
}

const list = (pages: Set<string> | undefined) =>
  pages && pages.size > 0 ? [...pages].map((p) => `\`${p}\``).join(", ") : "not shown yet";

const interimRows = Object.values(placeholders).map(
  (p) => `| ${p.interim} | ${p.pages.map((page) => `\`${page}\``).join(", ")} | ${p.needs} |`,
);
const bracketRows = [...tokenPages.entries()].map(
  ([token, pages]) =>
    `| ${token} | ${list(pages)} | ${Object.values(placeholders).some((p) => p.token === token) ? "Registered" : "**Not registered in site.ts**"} |`,
);

const stockRows = Object.values(images)
  .filter((slot) => slot.file && slot.credit)
  .map(
    (slot) =>
      `| \`${slot.id}\` | ${slot.alt} (${slot.credit?.photographer}, ${slot.credit?.license}) | ${slot.caption} |`,
  );
const emptyRows = Object.values(images)
  .filter((slot) => slotPages.has(slot.id))
  .map((slot) => `| \`${slot.id}\` | ${slot.caption} | ${list(slotPages.get(slot.id))} |`);

const doc = `# Placeholders Tarley needs to fill

Generated by \`npm run placeholders\` from the built site. Do not edit by hand; change \`src/content/site.ts\` and rebuild.

Until Tarley supplies its own content, the site shows interim copy written only from confirmed facts (address, hours, services, reply time) and stock photos that never claim to show Tarley's people or office. Replace each item below when the real content is ready.

## Interim text

To replace one, edit \`interim\` on the matching entry in \`placeholders\` in \`site.ts\`.

| Text now on the site | Pages | What Tarley supplies |
| --- | --- | --- |
${interimRows.join("\n")}

## Bracketed placeholders still showing

${bracketRows.length > 0 ? `| Placeholder | Pages | Status |\n| --- | --- | --- |\n${bracketRows.join("\n")}` : "None. Every placeholder currently shows interim text."}

## Photos

Stock and third-party photos stand in for Tarley's own. To replace one, put the photo in \`assets/photos/{slot}.jpg\`, remove \`credit\` from the slot in \`site.ts\` (or update it), update \`alt\`, then run \`npm run assets\` and \`npm run credits\`.

| Slot | Photo now | Ideal shot from Tarley |
| --- | --- | --- |
${stockRows.join("\n")}
${emptyRows.length > 0 ? `\nEmpty photo slots:\n\n| Slot | Shot needed | Pages |\n| --- | --- | --- |\n${emptyRows.join("\n")}\n` : ""}
## Facts to confirm

| Item | Current value | Why it needs a check |
| --- | --- | --- |
${factsToConfirm.map((f) => `| ${f.item} | ${f.value} | ${f.why} |`).join("\n")}
`;

await writeFile("PLACEHOLDERS.md", doc);
console.log(
  `PLACEHOLDERS.md: ${interimRows.length} interim texts, ${bracketRows.length} bracketed placeholders, ${stockRows.length} stock photos, ${emptyRows.length} empty photo slots`,
);
